<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<PackageVersion>2.1.27548.20260419</PackageVersion>
    	<Authors>Avalonia Team</Authors>
    	<Copyright>Copyright 2013-$([System.DateTime]::Now.ToString(`yyyy`)) &#169; The AvaloniaUI Project</Copyright>		
		<PackageProjectUrl>https://avaloniaui.net</PackageProjectUrl>
		<RepositoryUrl>https://github.com/AvaloniaUI/angle/</RepositoryUrl>
		<PackageIcon>Icon.png</PackageIcon>
        <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageDescription>Avalonia is a cross-platform UI framework for .NET providing a flexible styling system and supporting a wide range of Operating Systems such as Windows, Linux, macOS and with experimental support for Android, iOS and WebAssembly.</PackageDescription>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="..\out\x64\av_libglesv2.dll">
			<Pack>true</Pack>
			<PackagePath>runtimes\win-x64\native</PackagePath>
		</Content>

		<Content Include="..\out\x86\av_libglesv2.dll">
			<Pack>true</Pack>
			<PackagePath>runtimes\win-x86\native</PackagePath>
		</Content>

		<Content Include="..\out\arm64\av_libglesv2.dll">
			<Pack>true</Pack>
			<PackagePath>runtimes\win-arm64\native</PackagePath>
		</Content>

    	<None Include="$(MSBuildThisFileDirectory)/Icon.png">
			<Pack>true</Pack>
			<PackagePath></PackagePath>
		</None>
    	<None Include="$(MSBuildThisFileDirectory)/../LICENSE">
			<Pack>true</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>

</Project>
